name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - run: npm install
      env:
        PAGE_ACCESS_TOKEN :  ${{ secrets.PAGE_ACCESS_TOKEN }}
        CI: true
